/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author isabe
 */
package E_Learning;
import net.sourceforge.jFuzzyLogic.FIS;
import net.sourceforge.jFuzzyLogic.plot.JFuzzyChart;
import net.sourceforge.jFuzzyLogic.rule.Rule;

public class GUI_ELearning extends javax.swing.JFrame {

    /**
     * Creates new form GUI_ELearning
     */
    public GUI_ELearning() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label_pAbandono = new javax.swing.JLabel();
        label_familiaridad = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        label_hInvertibles = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cajapAbandono = new javax.swing.JTextField();
        cajaHInvertible = new javax.swing.JTextField();
        cajaEdad = new javax.swing.JTextField();
        cajaFamiliaridad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        respuesta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bienvenido");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 30, 110, 22);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Aquí podrás encontrar cursos a tu medida");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 60, 270, 17);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Por favor llene los campos de abajo, los que tienen asterisco son obligatorios");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 80, 400, 20);

        label_pAbandono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_pAbandono.setForeground(new java.awt.Color(255, 255, 255));
        label_pAbandono.setText("Porcentaje de abandono del curso*");
        label_pAbandono.setToolTipText("Porcentaje entre 0 y 100 aproximado en el que el usuario abandona los cursos");
        jPanel1.add(label_pAbandono);
        label_pAbandono.setBounds(20, 130, 240, 20);

        label_familiaridad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_familiaridad.setForeground(new java.awt.Color(255, 255, 255));
        label_familiaridad.setText("Familiaridad con los temas que se tratan en el curso* ");
        label_familiaridad.setToolTipText("En una escala del 0 al 100 que tan familiarizado está con el tema que desea estudiar");
        jPanel1.add(label_familiaridad);
        label_familiaridad.setBounds(20, 180, 360, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Edad*");
        jLabel6.setToolTipText("En una escala de azul a tomate, ¿cuál es tu animal preferido?");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 280, 40, 20);

        label_hInvertibles.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_hInvertibles.setForeground(new java.awt.Color(255, 255, 255));
        label_hInvertibles.setText("Horas por día para invertirle al curso*");
        label_hInvertibles.setToolTipText("Con cuantas horas al día (entre 0 y 24)  cuenta para avanzar en el curso");
        jPanel1.add(label_hInvertibles);
        label_hInvertibles.setBounds(20, 230, 290, 20);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Hacer mágia");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(180, 320, 120, 30);

        cajapAbandono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(cajapAbandono);
        cajapAbandono.setBounds(270, 130, 60, 26);

        cajaHInvertible.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(cajaHInvertible);
        cajaHInvertible.setBounds(320, 230, 60, 26);

        cajaEdad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(cajaEdad);
        cajaEdad.setBounds(80, 280, 60, 26);

        cajaFamiliaridad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(cajaFamiliaridad);
        cajaFamiliaridad.setBounds(390, 180, 60, 26);

        respuesta.setEditable(false);
        respuesta.setColumns(20);
        respuesta.setLineWrap(true);
        respuesta.setRows(5);
        jScrollPane1.setViewportView(respuesta);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 370, 370, 200);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        double edad, familiaridad, hInvertible, pAbandono;
        String response;
        
        //Load FIS file
        String fileName = "src/E_Learning/E_Learning.fcl";
        FIS fis = FIS.load(fileName, true);
        // Error while loading?
        if (fis == null) {
            System.err.println("Can't load file: '" + fileName + "'");
            return;
        }
        // Set vbles
        if (cajaEdad.getText().equals("") || cajaFamiliaridad.getText().equals("") || cajaHInvertible.equals("") || cajapAbandono.equals("")) {
            response = "Por favor llene TODOS los campos con asterisco, como de dijimos arribita.";
        }else{
            try{
                edad = Double.parseDouble(cajaEdad.getText());
                familiaridad = Double.parseDouble(cajaFamiliaridad.getText());
                hInvertible = Double.parseDouble(cajaHInvertible.getText());
                pAbandono = Double.parseDouble(cajapAbandono.getText());
            
                // Set inputs
                fis.setVariable("edad", edad);
                fis.setVariable("familiaridad", familiaridad);
                fis.setVariable("hInvertible", hInvertible);
                fis.setVariable("pAbandono", pAbandono);

                // Evaluate
                fis.evaluate();

                // Show
                JFuzzyChart.get().chart(fis.getFunctionBlock("recomendador"));
                Double d = Math.round(fis.getVariable("dRecomendacion").getLatestDefuzzifiedValue()*100.0)/100.0;
                Double e = Math.round(fis.getVariable("tExigido").getLatestDefuzzifiedValue()*100.0)/100.0;
                response = "La dificultad del curso recomendada para el usuario es: " + d
                        + ". Es decir que en una escala del 0 al 20 entre mas cerca se "
                        + "halle del 20, va a necesitar mas conocimientos previos y ha de esperar un desafío mucho mayor."
                        + "\n El tiempo que se recomienda que exija el curso elegido "
                        + "por el usuario es de: " + e + " horas";
                
            }catch (Exception e){
                response = "Todos los datos deben ser numéricos";
            }
        }
        respuesta.setText(response);   
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
                
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GUI_ELearning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cajaEdad;
    private javax.swing.JTextField cajaFamiliaridad;
    private javax.swing.JTextField cajaHInvertible;
    private javax.swing.JTextField cajapAbandono;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_familiaridad;
    private javax.swing.JLabel label_hInvertibles;
    private javax.swing.JLabel label_pAbandono;
    private javax.swing.JTextArea respuesta;
    // End of variables declaration//GEN-END:variables
}
