/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author isabe
 */
package E_Learning;
import net.sourceforge.jFuzzyLogic.FIS;
import net.sourceforge.jFuzzyLogic.plot.JFuzzyChart;
import net.sourceforge.jFuzzyLogic.rule.Rule;

public class GUI_ELearning extends javax.swing.JFrame {

    /**
     * Creates new form GUI_ELearning
     */
    public GUI_ELearning() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cajapAbandono = new javax.swing.JTextField();
        cajaHInvertible = new javax.swing.JTextField();
        cajaEdad = new javax.swing.JTextField();
        cajaFamiliaridad = new javax.swing.JTextField();
        respuesta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bienvenido");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 20, 90, 21);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("(algo super interesante)");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 50, 160, 17);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Porcentaje de abandono del curso");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 110, 240, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Familiaridad con los temas que se tratan en el curso ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 140, 350, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Edad");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 220, 40, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Horas por semana para invertirle al curso");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 180, 280, 20);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Hacer mágia");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(180, 280, 120, 30);

        cajapAbandono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(cajapAbandono);
        cajapAbandono.setBounds(270, 110, 60, 26);

        cajaHInvertible.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(cajaHInvertible);
        cajaHInvertible.setBounds(320, 180, 60, 26);

        cajaEdad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(cajaEdad);
        cajaEdad.setBounds(70, 220, 60, 26);

        cajaFamiliaridad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(cajaFamiliaridad);
        cajaFamiliaridad.setBounds(380, 140, 60, 26);

        respuesta.setEditable(false);
        jPanel1.add(respuesta);
        respuesta.setBounds(20, 330, 430, 240);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        int edad, familiaridad, hInvertible, pAbandono;
        
        //Load FIS file
        String fileName = "src/E_Learning/E_Learning.fcl";
        FIS fis = FIS.load(fileName, true);
        // Error while loading?
        if (fis == null) {
            System.err.println("Can't load file: '" + fileName + "'");
            return;
        }
        // Set vbles
        edad = Integer.parseInt(cajaEdad.getText());
        familiaridad = Integer.parseInt(cajaFamiliaridad.getText());
        hInvertible = Integer.parseInt(cajaHInvertible.getText());
        pAbandono = Integer.parseInt(cajapAbandono.getText());
        
        // Set inputs
        fis.setVariable("edad", edad);
        fis.setVariable("familiaridad", familiaridad);
        fis.setVariable("hInvertible", hInvertible);
        fis.setVariable("pAbandono", pAbandono);
        
        // Evaluate
        fis.evaluate();
        
        // Show
        JFuzzyChart.get().chart(fis.getFunctionBlock("recomendador"));
        Double d = fis.getVariable("dificultad").getLatestDefuzzifiedValue();
        Double e = fis.getVariable("tExigido").getLatestDefuzzifiedValue();
        respuesta.setText("Para los valores de salida el grado de pertenencia es: " + d + "con" + e);
    }//GEN-LAST:event_jButton1MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
                
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GUI_ELearning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cajaEdad;
    private javax.swing.JTextField cajaFamiliaridad;
    private javax.swing.JTextField cajaHInvertible;
    private javax.swing.JTextField cajapAbandono;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField respuesta;
    // End of variables declaration//GEN-END:variables
}
